// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_SZ-sK2BhH520QPzLXuoLbdgsGH5FiSs',
    appId: '1:908453874362:web:fe5e8a2c8afa233561d083',
    messagingSenderId: '908453874362',
    projectId: 'jawan-hackathon',
    authDomain: 'jawan-hackathon.firebaseapp.com',
    storageBucket: 'jawan-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1HgoD9ahsGCNvUT97a2asgmupS6qI4w',
    appId: '1:908453874362:android:3f7c2a0a865eb24061d083',
    messagingSenderId: '908453874362',
    projectId: 'jawan-hackathon',
    storageBucket: 'jawan-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Z4n__8uuC_ixuC2i1JgxQdbcR09hGoU',
    appId: '1:908453874362:ios:3381cc6b9322fa0361d083',
    messagingSenderId: '908453874362',
    projectId: 'jawan-hackathon',
    storageBucket: 'jawan-hackathon.appspot.com',
    iosClientId: '908453874362-f2jm6g6o1ucehcd86vs7o9r64ohvhk4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.minihackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Z4n__8uuC_ixuC2i1JgxQdbcR09hGoU',
    appId: '1:908453874362:ios:3381cc6b9322fa0361d083',
    messagingSenderId: '908453874362',
    projectId: 'jawan-hackathon',
    storageBucket: 'jawan-hackathon.appspot.com',
    iosClientId: '908453874362-f2jm6g6o1ucehcd86vs7o9r64ohvhk4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.minihackathon',
  );
}
